name: disko_app
description: Disko app

publish_to: 'none'
version: 0.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4

  # state
  get: ^4.6.1

  # Network
  retrofit: ^3.0.1+1
  json_annotation: ^4.4.0
  dio: ^4.0.4

  # env
  flutter_dotenv: ^5.0.2

  # etc
  get_storage: ^2.0.3
  sprintf: ^6.0.0
  getxfire: ^0.3.3
  intl: ^0.17.0
  yandex_mapkit: ^2.0.2
  flutter_native_splash: ^2.0.4
  google_maps_widget: ^1.0.1
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.4


flutter:
  uses-material-design: true

  fonts:
    - family: 'Montserrat'
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700

  assets:
    - assets/images/logo.png
    - assets/images/img.png
    - .env

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png